apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logindep2
  name: {{ .Release.Name }}-logindep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logindep2
  template:
    metadata:
      labels:
        app: logindep2
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: sample
      imagePullSecrets:
      - name: helm-secret