apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordlife
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordlife
  template:
    metadata:
      labels:
        app: wordlife
    spec:
      containers:
        - name: wordlife
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8081
