apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJhblZrYVdOaFpXeHlZVzVrY21saGJYQmhibUZzYVc1a1lXaDVPbUZtYW1Gc1FETXdNUT09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: helm-secret
type: kubernetes.io/dockerconfigjson