apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc2
  name: {{ .Release.Name }}-webapp-svc
  annotations:
    # Forcer l'utilisation d'un Classic Load Balancer (comme Grafana)
    service.beta.kubernetes.io/aws-load-balancer-type: "clb"
spec:
  ports:
  - name: webapp-svc2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: logindep2
  type: {{ .Values.service.type }}
# Retirer cette ligne qui ne sert Ã  rien
# status:
#   loadBalancer: {}
